<!--
  Copyright (c) 2025 Maarten Jacobs
  All rights reserved.
  This file is part of tomboy-modern and was created specifically for this project.
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
    <AssemblyName>Tomboy</AssemblyName>
    <RootNamespace>Tomboy</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>

    <Configuration>Debug</Configuration>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <PublishTrimmed>true</PublishTrimmed>
    <StripSymbols>false</StripSymbols>

    <BaseOutputPath>$(MSBuildProjectDirectory)/build</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)/bin</OutputPath>
    <IntermediateOutputPath>$(BaseOutputPath)/obj</IntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Mono.Addins">
      <HintPath>lib/Mono.Addins.dll</HintPath>
    </Reference>
    <!-- <Reference Include="Mono.Addins.Gui">
      <HintPath>lib/Mono.Addins.Gui.dll</HintPath>
    </Reference> -->
    <Reference Include="Mono.Addins.Setup">
      <HintPath>lib/Mono.Addins.Setup.dll</HintPath>
    </Reference>
    <Reference Include="gconf-sharp">
      <HintPath>lib/gconf-sharp.dll</HintPath>
    </Reference>
    <Reference Include="gnome-sharp">
      <HintPath>lib/gnome-sharp.dll</HintPath>
    </Reference>
    <Reference Include="dbus-sharp">
      <HintPath>lib/dbus-sharp.dll</HintPath>
    </Reference>
    <Reference Include="dbus-sharp-glib">
      <HintPath>lib/dbus-sharp-glib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <DefineConstants>ENABLE_DBUS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <DefineConstants>WIN32</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <Compile Remove="Tomboy/MacApplication.cs" />
    <Compile Remove="Tomboy/MacFactory.cs" />

    <Compile Remove="Tomboy/Defines.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
    <Compile Remove="Tomboy/MacApplication.cs" />
    <Compile Remove="Tomboy/MacFactory.cs" />

    <Compile Remove="Tomboy/Defines.WIN32.cs" />
    <Compile Remove="Tomboy/ManagedWinapi.EventDispatchingNativeWindow.cs" />  
    <Compile Remove="Tomboy/ManagedWinapi.Hotkey.cs" />
    <Compile Remove="Tomboy/WindowsKeybinder.cs" />
    <Compile Remove="Tomboy/WindowsFactory.cs" />
    <Compile Remove="Tomboy/JumpListManager.cs " />
    <Compile Remove="Tomboy/WindowsInterop.cs" />
    <Compile Remove="Tomboy/WindowsApplication.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tomboy/Applet.cs" />
    <Compile Remove="Tomboy/**/*-old.cs" />
    <Compile Remove="Tomboy/Addins/**/*.cs" />
    <Compile Remove="test/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="data/UIManagerLayout.xml">
      <LogicalName>UIManagerLayout.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Tomboy/Tomboy.addin.xml">
      <LogicalName>Tomboy.addin.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="data/tomboy-note-clipboard-html.xsl">
      <LogicalName>tomboy-note-clipboard-html.xsl</LogicalName>
    </EmbeddedResource>
    <JumpListIcons Include="data/icons/tomboy.ico;data/icons/new_note.ico;data/icons/note.ico;data/icons/search.ico" />
  </ItemGroup>

<!-- TO DO: Figure out distribution of files
  <ItemGroup>
    <None Include="Tomboy\**\*.glade" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Tomboy\**\*.xml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Tomboy\**\*.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
-->

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.24.24.95" />
    <PackageReference Include="mono.posix" Version="7.1.0-final.1.21458.1" />
    <PackageReference Include="Mono.Unix" Version="7.1.0-final.1.21458.1" />
    <PackageReference Include="Tmds.DBus" Version="0.21.2" />
  </ItemGroup>

  <Target Name="AddRuntimeScaffolding" AfterTargets="Build">
<!--    <ItemGroup>
      <RuntimeSharedObjects Include="/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so" />
      <RuntimeSharedObjects Include="/usr/lib/x86_64-linux-gnu/libglib-2.0.so" />
      <RuntimeSharedObjects Include="/usr/lib/x86_64-linux-gnu/libgobject-2.0.so" />
    </ItemGroup>
    <Copy SourceFiles="@(RuntimeSharedObjects)"
          DestinationFiles="@(RuntimeSharedObjects->'$(OutputPath)/runtimes/linux-x64/native/%(fileName)-0.dll')"
          SkipUnchangedFiles="true"
          Retries="2"
          RetryDelayMilliseconds="500" />

    <ItemGroup>
      <RuntimeDynamicLinkLibraries Include="lib/*" />
    </ItemGroup>
    <Copy SourceFiles="@(RuntimeDynamicLinkLibraries)"
          DestinationFolder="$(OutputPath)/lib"
          SkipUnchangedFiles="true"
          Retries="2"
          RetryDelayMilliseconds="500" />
    <Copy SourceFiles="/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so"
          DestinationFiles="$(OutputPath)/runtimes/linux-x64/native/libgtk-win32-2.0-0.dll"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="/source/tomboy/stage/lib/tomboy/libtomboy.so"
          DestinationFiles="$(OutputPath)/runtimes/linux-x64/native/libtomboy.so"
          SkipUnchangedFiles="true" />
-->
    <ItemGroup>
      <Icons Include="data/icons/*.png" />
      <Icons Include="data/icons/*.ico" />
    </ItemGroup>
    <Copy SourceFiles="@(Icons)"
          DestinationFolder="$(BaseOutputPath)/share/icons"
          SkipUnchangedFiles="true"
          Retries="2"
          RetryDelayMilliseconds="500" />
  </Target>
</Project>