<!--
  Copyright (c) 2025 Maarten Jacobs
  All rights reserved.
  This file is part of tomboy-modern and was created specifically for this project.
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>AdvPrefTab</RootNamespace>
    <AssemblyName>AdvancedPreferences</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>

    <BaseOutputPath>$(TomboyOutputDir)</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)/bin</OutputPath>
    <IntermediateOutputPath>$(BaseOutputPath)/obj</IntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AdvancedPreferencesAddin.cs" />
    <Compile Include="EnableStartupNotesPreference.cs" />
    <Compile Include="MenuMinMaxNoteCountPreference.cs" />
    <EmbeddedResource Include="AdvancedPreferences.addin.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Tomboy.csproj" />
  </ItemGroup>

</Project>